#!/usr/bin/env bash
# ci/ci.sh - CI workflow file generator
#
# Incorporates patterns from:
#   ghazzor/Xanmod-Kernel-Builder      - GitHub Actions Clang/LLVM workflow
#   tsirysndr/vmlinux-builder          - Multi-arch CI, release artifact upload
#   rizalmart/puppy-linux-kernel-maker - Branch-per-version workflow pattern
#   Biswa96/android-kernel-builder     - Android CI workflow
#   osresearch/linux-builder           - Appliance/firmware CI

ci_usage() {
    cat <<EOF
lkf ci - Generate CI workflow files

USAGE: lkf ci [options]

OPTIONS:
  --provider <name>   CI provider: github [default: github]
  --arch <list>       Comma-separated architectures [x86_64]
  --flavor <name>     Kernel flavor: mainline, xanmod, android [mainline]
  --llvm              Include LLVM/Clang build
  --lto <mode>        LTO mode: none, thin, full [none]
  --output <path>     Output file path [.github/workflows/kernel.yml]
  --release           Include release artifact upload step
  --matrix            Generate a matrix build (one job per arch)

EXAMPLES:
  lkf ci --arch x86_64,aarch64 --llvm --lto full --release
  lkf ci --flavor android --arch aarch64 --output .github/workflows/android.yml
  lkf ci --flavor xanmod --llvm --matrix
EOF
}

ci_main() {
    local provider="github" arch_list="x86_64" flavor="mainline"
    local llvm=0 lto="none" output="" release=0 matrix=0

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --provider) provider="$2"; shift 2 ;;
            --arch)     arch_list="$2"; shift 2 ;;
            --flavor)   flavor="$2"; shift 2 ;;
            --llvm)     llvm=1; shift ;;
            --lto)      lto="$2"; shift 2 ;;
            --output)   output="$2"; shift 2 ;;
            --release)  release=1; shift ;;
            --matrix)   matrix=1; shift ;;
            --help|-h)  ci_usage; return 0 ;;
            *) lkf_die "Unknown option: $1" ;;
        esac
    done

    case "${provider}" in
        github) ci_generate_github "${arch_list}" "${flavor}" "${llvm}" \
                    "${lto}" "${output}" "${release}" "${matrix}" ;;
        *) lkf_die "Unsupported CI provider: ${provider}" ;;
    esac
}

ci_generate_github() {
    local arch_list="$1" flavor="$2" llvm="$3" lto="$4"
    local output="${5:-.github/workflows/kernel.yml}"
    local release="$6" matrix="$7"

    lkf_ensure_dir "$(dirname "${output}")"

    IFS=',' read -ra arches <<< "${arch_list}"

    # Build lkf build command flags
    local build_flags="--flavor ${flavor}"
    [[ "${llvm}" -eq 1 ]] && build_flags+=" --llvm"
    [[ "${lto}" != "none" ]] && build_flags+=" --lto ${lto}"

    lkf_step "Generating GitHub Actions workflow: ${output}"

    cat > "${output}" <<YAML
# Generated by lkf ci
# Kernel flavor: ${flavor} | LLVM: ${llvm} | LTO: ${lto}
# Architectures: ${arch_list}

name: Kernel Build

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*', '[0-9]*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Kernel version (e.g. 6.12)'
        required: true
        default: '6.12'

jobs:
YAML

    if [[ "${matrix}" -eq 1 ]]; then
        # Matrix build
        local arch_json
        arch_json=$(printf '"%s",' "${arches[@]}")
        arch_json="[${arch_json%,}]"

        cat >> "${output}" <<YAML
  build:
    name: Build (\${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: ${arch_json}

    steps:
      - uses: actions/checkout@v4

      - name: Install lkf
        run: |
          git clone https://github.com/your-org/lkf /opt/lkf
          echo "/opt/lkf" >> \$GITHUB_PATH

      - name: Install build dependencies
        run: lkf build --install-deps --version \${{ github.event.inputs.kernel_version || '6.12' }} ${build_flags} --arch \${{ matrix.arch }} --stop-after download

      - name: Build kernel
        run: |
          lkf build \\
            --version \${{ github.event.inputs.kernel_version || '6.12' }} \\
            ${build_flags} \\
            --arch \${{ matrix.arch }} \\
            --threads \$(nproc) \\
            --build-dir build/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-\${{ matrix.arch }}-\${{ github.event.inputs.kernel_version || '6.12' }}
          path: |
            build/*.deb
            build/*.rpm
            build/*.tar.gz
            build/bootx64.efi
          if-no-files-found: warn
YAML
    else
        # Individual jobs per arch
        for arch in "${arches[@]}"; do
            local runner="ubuntu-latest"
            local cross_flag=""
            [[ "${arch}" == "aarch64" ]] && cross_flag="--cross aarch64-linux-gnu-"

            cat >> "${output}" <<YAML
  build-${arch}:
    name: Build (${arch})
    runs-on: ${runner}

    steps:
      - uses: actions/checkout@v4

      - name: Install lkf
        run: |
          git clone https://github.com/your-org/lkf /opt/lkf
          echo "/opt/lkf" >> \$GITHUB_PATH

YAML
            if [[ "${llvm}" -eq 1 ]]; then
                cat >> "${output}" <<YAML
      - name: Install LLVM
        run: |
          wget -qO- https://apt.llvm.org/llvm.sh | sudo bash -s -- 19
          sudo apt-get install -y clang-19 lld-19 llvm-19
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-19 100
          sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/lld-19 100

YAML
            fi

            cat >> "${output}" <<YAML
      - name: Install build dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \\
            build-essential bison flex libncurses-dev libssl-dev \\
            libelf-dev bc lz4 zstd rsync cpio xz-utils bzip2 \\
            dwarves pahole debhelper
YAML
            if [[ "${arch}" == "aarch64" ]]; then
                cat >> "${output}" <<YAML
          sudo apt-get install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu
YAML
            fi

            cat >> "${output}" <<YAML

      - name: Build kernel
        run: |
          lkf build \\
            --version \${{ github.event.inputs.kernel_version || '6.12' }} \\
            ${build_flags} \\
            --arch ${arch} \\
            ${cross_flag} \\
            --threads \$(nproc) \\
            --build-dir build/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${arch}-\${{ github.event.inputs.kernel_version || '6.12' }}
          path: |
            build/*.deb
            build/*.rpm
            build/*.tar.gz
          if-no-files-found: warn

YAML
        done
    fi

    # Release job
    if [[ "${release}" -eq 1 ]]; then
        cat >> "${output}" <<YAML
  release:
    name: Create Release
    needs: [$(printf 'build-%s, ' "${arches[@]}" | sed 's/, $//')]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create checksums
        run: |
          find artifacts/ -type f | sort | xargs sha256sum > SHA256SUMS

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/*
            SHA256SUMS
          generate_release_notes: true
YAML
    fi

    lkf_info "GitHub Actions workflow written to: ${output}"
}
